### ISSUE TITLE
URL links are bad- point to wrong server

### ISSUE THREAD

**Issue by ACharbonneau** [ncbi/DbGaP-FHIR-API-Docs#4]
In the example, you start with:

`http://dbgap-api.ncbi.nlm.nih.gov/fhir/x1/ResearchStudy` and get the next page using the link inside the result, which is:

`https://dbgap-api-firewalled.ncbi.nlm.nih.gov/fhir/x1?_getpages=8776f07f-4b69-4260-86d1-13708db96d5e&_getpagesoffset=100&_count=100&_pretty=true&_bundletype=searchset`

The issue is that link is for a firewalled server, not the public server. The actual address to get the second page is:
`https://dbgap-api.ncbi.nlm.nih.gov//fhir/x1?_getpages=8776f07f-4b69-4260-86d1-13708db96d5e&_getpagesoffset=100&_count=100&_pretty=true&_bundletype=searchset`

In each page, all of the links (self, next and previous) are displayed as the secure firewall addresses rather than the public ones.  Inside each record the `fullUrl` value is also pointing at the firewalled data.

**Comment by RadixSeven** [comment]
Thank you. We are working on this issue and hope to resolve it soon.

*Edit*: I initially wrote "by Tuesday," but then checked my notes, and we don't have a timeline yet.

**Comment by RadixSeven** [comment]
@ACharbonneau http://dbgap-api.ncbi.nlm.nih.gov/fhir/x1/ResearchStudy works for me with the correct `self`, `next`, and `fullUrl` links. Please check that it is working for you. (Note: on pages after the second, the `previous` link will be incorrect, that is a separate issue stemming from the FHIR framework we use.)

**Comment by ACharbonneau** [comment]
the links do seem to work now, thanks
